LLM_CONFIG:
  openai_api_base: https://api.openai.com/v1
  openai_api_key: ''
  openai_api_type: open_ai
  openai_api_version: '2023-05-15'
  openai_frequency_penalty: 0.0
  openai_max_tokens: 2000
  openai_model: gpt-4
  openai_organization: ''
  openai_presence_penalty: 0.0
  openai_proxy: ''
  openai_request_timeout: 60
  openai_temperature: 0.7
  openai_top_p: 1.0
base_config:
  proxy:
    url: http://127.0.0.1:7890
base_tools:
  python27:
    path: ../Tools/python27/python27.exe
  python310:
    path: ../Tools/python3/python.exe
  strings:
    path: ../Tools/other/strings.exe
other_tools:
  EvtxECmd:
    path: ../Tools/EvtxECmd/EvtxECmd.exe
  RegistryExplorer:
    path: ../Tools/RegistryExplorer/RegistryExplorer.exe
tools:
  lovelypixelweaver:
    path: ../LovelymemLuxe/extensions/lovelypixelweaver.exe
  memprocfs:
    path: ../Tools/MemProcFS/MemProcFS.exe
  volatility2_plugin:
    path: ../Tools/volatility2_plugin
  volatility2_python:
    path: ../Tools/volatility2_python/vol.py
  volatility3:
    path: ../Tools/volatility3/vol.py
